issue_prefix: flashloaner

auto_sync:
  export_to_jsonl: true
  debounce_seconds: 5

auto_import:
  from_jsonl: true
  when_newer: true

daemon:
  auto_start: true

dolt:
  host: 10.10.20.138
  port: 3306
  database: beads
  user: beads
  auto-commit: "on"
